version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "${DB_PORT}:5432"
